using DSAUtils.Settings.Aventurien;

namespace Magehelper.Core;

public partial class Character
{
    private int _au;
    private int _le;
    private int _ae;
    private readonly Core _core = Core.GetInstance();
    public int Mu { get; set; }
    public int Kl { get; set; }
    public int In { get; set; }
    public int Ch { get; set; }
    public int Ff { get; set; }
    public int Ge { get; set; }
    public int Ko { get; set; }
    public int Kk { get; set; }
    public int Mr { get; set; }
    public int AuP { get; set; }
    public int LeP { get; set; }
    public int AsP { get; set; }
    public string LinkedCharacter { get; private set; } = string.Empty;
    // ReSharper disable once UnusedAutoPropertyAccessor.Local
    public bool IsLoaded { get; private set; }
    public CharacterType LinkedCharacterType { get; set; } = CharacterType.None;
    /// <summary>
    /// The skills that character has.
    /// </summary>
    public ReadOnlyCollection<Ability>? Skills { get; private set; }
    /// <summary>
    /// The Spells this Character knows.
    /// </summary>
    public ReadOnlyCollection<CharacterSpell>? Spells { get; private set; }
    /// <summary>
    /// The Rituals this Character knows.
    /// </summary>
    public ReadOnlyCollection<CharacterRitual>? Rituals { get; private set; }

    public Dictionary<string, int> Rkw { get; } = [];

    public Charakter? Data { get; private set; }
    /// <summary>
    /// Constructor
    /// </summary>
    public Character()
    {
        _core.Character = this;

        if (_core.FileAup)
        {
            AuP = _core.FileAupValue;
        }

        if (_core.FileLep)
        {
            LeP = _core.FileLepValue;
        }

        if (_core.FileAsp)
        {
            AsP = _core.FileAspValue;
        }
    }

    /// <summary>
    /// Loads all characters that can be used.
    /// </summary>
    /// <returns>An array of <see cref="DSAUtils.HeldentoolInterop.Charakter"/></returns>
    /// <exception cref="FileNotFoundException"/>
    public Charakter[] GetCharactersFromTool()
    {
        return HeldentoolInterop.IsInstalled() ? HeldentoolInterop.GetByAE() : throw new FileNotFoundException("\"Helden-Software\" is not installed.");
    }
    /// <summary>
    /// Load an character.
    /// </summary>
    /// <param name="identifier">file path or signature (value generated by 'Helden-Software')/></param>
    public void LoadCharacter(string identifier)
    {
        Charakter character = File.Exists(identifier)
            ? HeldentoolInterop.LoadFromXML(identifier)
            : HeldentoolInterop.GetBySignature(identifier);

        ResetTool();
        Data = character;
        LinkedCharacter = identifier;

        List<CharacterSpell> spells = [];
        List<CharacterRitual> rituals = [];
        List<string> ritualList =
        [
            .. Aventurien.Rituale.druidenritual,
            .. Aventurien.Rituale.durrodunritual,
            .. Aventurien.Rituale.elfenlied,
            .. Aventurien.Rituale.hexenfluch,
            .. Aventurien.Rituale.kristallomantenritual,
            .. Aventurien.Rituale.kugelzauber,
            .. Aventurien.Rituale.schalenzauber,
            .. Aventurien.Rituale.schamanenritual,
            .. Aventurien.Rituale.stabzauber,
            .. Aventurien.Rituale.trommelzauber,
            .. Aventurien.Rituale.zaubertanz,
            .. Aventurien.Rituale.zibiljaritual,
        ];

        Skills = character.Talente.ToList().AsReadOnly();

        foreach (Ability ability in character.Eigenschaften)
        {
            switch (ability.Name)
            {
                case "Mut":
                    Mu = ability.Wert;
                    break;
                case "Klugheit":
                    Kl = ability.Wert;
                    break;
                case "Intuition":
                    In = ability.Wert;
                    break;
                case "Charisma":
                    Ch = ability.Wert;
                    break;
                case "Fingerfertigkeit":
                    Ff = ability.Wert;
                    break;
                case "Gewandtheit":
                    Ge = ability.Wert;
                    break;
                case "Konstitution":
                    Ko = ability.Wert;
                    break;
                case "Körperkraft":
                    Kk = ability.Wert;
                    break;
                case "Magieresistenz":
                    Mr = ability.Wert;
                    break;
                case "Ausdauer":
                    _au = ability.Wert;

                    if (!_core.FileAup)
                    {
                        AuP = ability.Wert;
                    }

                    break;
                case "Lebensenergie":
                    _le = ability.Wert;

                    if (!_core.FileLep)
                    {
                        LeP = ability.Wert;
                    }

                    break;
                case "Astralenergie":
                    _ae = ability.Wert;

                    if (!_core.FileAsp)
                    {
                        AsP = ability.Wert;
                    }

                    break;
            }
        }

        foreach (Ability ability in character.Talente)
        {
            switch (ability.Name)
            {
                case "Ritualkenntnis: Alchimist":
                    Rkw["Alchimist"] = ability.Wert;
                    break;
                case "Ritualkenntnis: Derwisch":
                    Rkw["Derwisch"] = ability.Wert;
                    break;
                case "Ritualkenntnis: Druide":
                    Rkw["Druide"] = ability.Wert;
                    break;
                case "Ritualkenntnis: Durro-Dun":
                    Rkw["Durro-Dun"] = ability.Wert;
                    break;
                case "Ritualkenntnis: Geode":
                    Rkw["Geode"] = ability.Wert;
                    break;
                case "Ritualkenntnis: Gildenmagie":
                    Rkw["Gildenmagie"] = ability.Wert;
                    break;
                case "Ritualkenntnis: Glyphenkunde(Alhani)":
                    Rkw["Glyphenkunde(Alhani)"] = ability.Wert;
                    break;
                case "Ritualkenntnis: Hexe":
                    Rkw["Hexe"] = ability.Wert;
                    break;
                case "Ritualkenntnis: Kristallomantie":
                    Rkw["Kristallomantie"] = ability.Wert;
                    break;
                case "Ritualkenntnis: Petromantie":
                    Rkw["Petromantie"] = ability.Wert;
                    break;
                case "Ritualkenntnis: Runenzauberei":
                    Rkw["Runenzauberei"] = ability.Wert;
                    break;
                case "Ritualkenntnis: Scharlatan":
                    Rkw["Scharlatan"] = ability.Wert;
                    break;
                case "Ritualkenntnis: Seher":
                    Rkw["Seher"] = ability.Wert;
                    break;
                case "Ritualkenntnis: Zaubertänzer":
                    Rkw["Zaubertänzer"] = ability.Wert;
                    break;
                case "Ritualkenntnis: Zibilja":
                    Rkw["Zibilja"] = ability.Wert;
                    break;
            }
        }

        foreach (Ability spell in character.Zauber)
        {
            try
            {
                string spellName = spell.Name.Split('(')[0].Trim();

                Zauber spellData = spell.Repraesentation == "Magiedilletant"
                    ? Aventurien.Zauber.GetByName(spellName)
                    : Aventurien.Zauber.GetByName(spellName, Aventurien.Zauber.RepToEnum(spell.Repraesentation!));

                spells.Add(new()
                {
                    Name = spell.Name,
                    Representation = spell.Repraesentation!,
                    Attributes = spellData.Eigenschaften.Split('/'),
                    Komplex = spellData.Komplexitaet,
                    Characteristics = spellData.MerkmaleToString(),
                    Value = spell.Wert
                });
            }
            catch (Exception ex)
            {
                //TODO: Log
                Console.WriteLine(ex);
            }
        }

        foreach (string sf in character.Sonderfertigkeiten)
        {
            foreach (string ritual in ritualList)
            {
                if (HeldentoolInterop.Rename(sf, Name.Offi) != ritual)
                {
                    continue;
                }

                string ritualName = ritual;
                string ritualAttributes = string.Empty;
                string ritualSkill;
                int[] ritualMod = [];
                RitualType ritualType = RitualType.Ritual;
                dynamic ritualData = Aventurien.Rituale.GetByName(ritualName);

                if (!_core.UseHeldentoolNames)
                {
                    ritualName = ((IRitual)ritualData).Name;
                }

                switch (ritualData)
                {
                    case Schamanenritual s:
                        ritualSkill = s.Ritualkenntnis;
                        ritualType = RitualType.Shaman;

                        break;
                    case Trommelzauber t:
                        ritualAttributes = t.Ritualprobe;
                        ritualSkill = t.Ritualprobe;
                        ritualMod = [t.Musizierenprobe, t.RitualErschwernis];
                        ritualType = RitualType.Drum;

                        break;
                    default:
                        ritualAttributes = ((Ritual)ritualData).Ritualprobe;
                        ritualSkill = ((Ritual)ritualData).Ritualkenntnis;
                        ritualMod = [((Ritual)ritualData).RitualErschwernis];

                        break;
                }

                rituals.Add(new() { Name = ritualName, Attributes = ritualAttributes, Skill = ritualSkill, Mod = ritualMod, Type = ritualType });
            }
        }

        Spells = spells.AsReadOnly();
        Rituals = rituals.AsReadOnly();
        IsLoaded = true;
    }

    public void ToggleLinkCharacterToFile()
    {
        if (LinkedCharacterType == CharacterType.None)
        {
            LinkedCharacterType = File.Exists(LinkedCharacter) ? CharacterType.File : CharacterType.HeldenSoftware;
        }
        else
        {
            LinkedCharacterType = CharacterType.None;
        }
    }

    /// <summary>
    /// Resets the instance of this class. (only used by <see cref="Core.ResetTool"/>.)
    /// </summary>
    internal void ResetTool()
    {
        _au = 0;
        _le = 0;
        _ae = 0;
        Mu = 0;
        Kl = 0;
        In = 0;
        Ch = 0;
        Ff = 0;
        Ge = 0;
        Ko = 8;
        Kk = 8;
        Mr = 0;
        AuP = 0;
        LeP = 0;
        AsP = 0;
        Skills = null;
        Spells = null;
        Rituals = null;
        IsLoaded = false;
        Data = null;
        LinkedCharacter = string.Empty;
        LinkedCharacterType = CharacterType.None;
    }

    public void ResetAuP()
    {
        AuP = _au;
        _core.FileChanged = true;
    }

    public void ResetLeP()
    {
        LeP = _le;
        _core.FileChanged = true;
    }

    public void ResetAsP()
    {
        AsP = _ae;
        _core.FileChanged = true;
    }

    public (int pointsLeft, int[] rollData, string textResult) RollSpell(CharacterSpell spell)
    {
        return GetResult(spell.Attributes, spell.Value, 0);
    }

    public (int pointsLeft, int[] rollData, string textResult) RollRitual(CharacterRitual ritual)
    {
        (int, int[], string) returnData;

        switch (ritual.Type)
        {
            case RitualType.Shaman:
                {
                    (string[], int) skillData = GetSkillData(ritual.Skill);
                    returnData = GetResult(skillData.Item1, skillData.Item2, 0);
                    break;
                }
            case RitualType.Drum:
                {
                    (string[], int) skillData = GetSkillData("Musizieren");
                    (int, int[], string) skillResult = GetResult(skillData.Item1, skillData.Item2, ritual.Mod[0]);

                    if (skillResult.Item1 >= 0 && !skillResult.Item3.Contains("Patzer"))
                    {
                        int modvalue = ritual.Mod[1] - skillResult.Item1;
                        returnData = GetResult(ritual.Attributes.Split('/'), Rkw["Derwisch"], modvalue);

                    }
                    else
                    {
                        string failedText = "Misslungen (Musizieren)";
                        if (skillResult.Item3 != string.Empty)
                        {
                            failedText += "; " + skillResult.Item3;
                        }
                        returnData = (skillResult.Item1, skillResult.Item2, failedText);
                    }

                    break;
                }
            case RitualType.Ritual:
            default:
                {
                    string[] attributes;
                    int value;

                    if (Sonderfertigkeiten.GetByGroup(Sonderfertigkeitengruppe.Ritualkenntnis).Contains(ritual.Skill))
                    {
                        attributes = ritual.Attributes.Split('/');
                        value = Rkw[ritual.Skill];
                    }
                    else
                    {
                        (string[], int) skillData = GetSkillData(ritual.Skill);
                        attributes = skillData.Item1;
                        value = skillData.Item2;
                    }

                    returnData = GetResult(attributes, value, ritual.Mod[0]);
                    break;
                }
        }
        return returnData;
    }

    private (int pointsLeft, int[] rollData, string textResult) GetResult(string[] attributes, int value, int mod)
    {
        int[] attrinuteValues = new int[3];

        for (int i = 0; i < 3; i++)
        {
            attrinuteValues[i] = attributes[i] switch
            {
                "MU" => Mu,
                "KL" => Kl,
                "IN" => In,
                "CH" => Ch,
                "FF" => Ff,
                "GE" => Ge,
                "KO" => Ko,
                "KK" => Kk,
                _ => attrinuteValues[i]
            };
        }

        return DSA.TaP(attrinuteValues, value, mod);
    }

    private (string[], int) GetSkillData(string skillname)
    {
        Talent skill = Aventurien.GetTalent(skillname);
        string[] attributes = skill.Eigenschaften.Split('/');
        int value = Skills!.Single(s => s.Name == skillname).Wert;
        return (attributes, value);
    }
}
